### ISSUE TITLE
ApplicationDbInitializer is not run?

### ISSUE THREAD

**Issue by synovia-1** [vincechan/PostgreSQL.AspNet.Identity.EntityFramework#1]
Hi. I'm new in ASP.NET so I apologize in advance if this is a too-simple-question.
I was able to setup the PostgreSQL.AspNet.Identity.EntityFramework into a new project. However, I wanted to have the default admin user(admin@example.com) initialized in ApplicationDbInitializer class in IdentityConfig.cs. Is it really not running if I use  PostgreSQL.AspNet.Identity.EntityFramework? Or did I miss something?

Thanks in advance and thanks a lot for creating this.

**Comment by vincechan** [comment]
Can you please post some code?

**Comment by vincechan** [comment]
It sounds like you are creating a custom Database Initializer ApplicationDbInitializer. Did you call Database.SetInitializer to set it as your database initializer? e.g.

```
Database.SetInitializer<ApplicationDbContext>(new ApplicationDbInitializer());
```

If you did, post the code that you have.

**Comment by vincechan** [comment]
I assumed the problem is ApplicationDbInitializer isn't set as the database initializer. If not, please let me know.
